server.port=${SERVER_PORT:8081}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/farm_to_home}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
